### ISSUE TITLE
Error after updating to eslint version 3.14.1

### ISSUE THREAD

**Issue by ericvaladas** [jmeas/pleaserc#18]
After updating eslint to version 3.14.1 I encounter an error when running eslint:
```
Cannot read config file: /Users/eric/Developer/formwood/node_modules/pleaserc/.eslintrc
Error: missed comma between flow collection entries at line 104, column 26:
        "no-warning-comments": "error",
                             ^
```
I removed the comment on line 103 out of curiosity and it solves the issue, so something must have happened recently to eslint's parser 🤷‍♂️.

**Comment by jmeas** [comment]
This is resolved in v2.3.1
